### ISSUE TITLE
Just FYI, a single-file, fast, serilog-compatible, message templates parser exists :)

### ISSUE THREAD

**Issue by adamchester** [TheAngryByrd/FsLibLog#1]
Just in case you were not aware, a single-file fast serilog-compatible message templates parser exists.

I'm not entirely sure how far you were planning to go with this library, and if it would even need such a thing, but I figured it couldn't hurt to let you know one exists :+1:

https://github.com/messagetemplates/messagetemplates-fsharp/blob//src/FsMtParser/FsMtParserFull.fs

This is not really an issue, so I'll just close it now :)

Happy hacking, and thanks for the library!

**Comment by TheAngryByrd** [comment]
Oh nice! I didn't realize there was a full source version!  I'm not sure if I want to get in the business of writing my own Log Provider.  I might do it as an example of implementing your own outside provider.
